version: '3.8'

services:
  genai-frontend:
    image: 831926608672.dkr.ecr.ap-south-1.amazonaws.com/genai-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=https://vlmpraid-ai.com/api
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - REACT_APP_PREVIEW_PASSWORD=Steelglass123!@
    restart: always
